export default [
  {
    _id: "345fc58a0b9849e391de3192",
    name: "Maria Silva",
    email: "maria.silva@example.com",
    emailVerified: true,
    image: "https://randomuser.me/api/portraits/women/1.jpg",
    username: "msilva",
  },
  {
    _id: "9b8cd55d2e724051a10a8641",
    name: "John Doe",
    email: "john.doe@example.com",
    emailVerified: true,
    image: "https://randomuser.me/api/portraits/men/1.jpg",
    username: "jdoe",
  },
  {
    _id: "ef6c2a7a07d84a2b9e61df6f",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    emailVerified: true,
    image: "https://randomuser.me/api/portraits/women/2.jpg",
    username: "jsmith",
  },
  {
    _id: "7f48a932b9fb4a299a1375a5",
    name: "William Johnson",
    email: "william.johnson@example.com",
    emailVerified: true,
    image: "https://randomuser.me/api/portraits/men/2.jpg",
    username: "wjohnson",
  },
  {
    _id: "635cd8c17b614f018bb64d5a",
    name: "Emily Wilson",
    email: "emily.wilson@example.com",
    emailVerified: true,
    image: "https://randomuser.me/api/portraits/women/3.jpg",
    username: "ewilson",
  },
  {
    _id: "6a1e6a102c8640c2956a9d6c",
    name: "Michael Brown",
    email: "michael.brown@example.com",
    emailVerified: true,
    image: "https://randomuser.me/api/portraits/men/3.jpg",
    username: "mbrown",
  },
  {
    _id: "4569d4b1176a4a1ca53617e7",
    name: "Sophia Lee",
    email: "sophia.lee@example.com",
    emailVerified: true,
    image: "https://randomuser.me/api/portraits/women/4.jpg",
    username: "slee",
  },
  {
    _id: "bc3cc3f2e1c14cc79234a087",
    name: "Christopher Garcia",
    email: "christopher.garcia@example.com",
    emailVerified: true,
    image: "https://randomuser.me/api/portraits/men/4.jpg",
    username: "cgarcia",
  },
];
