import { Prisma } from "@prisma/client";
import { populateParticipantsAndLatestMessage } from "../graphql/resolvers/conversation";

/* The data that is returned from createConversationMutation. */
export interface CreateConversationData {
  createConversation: {
    newConversationId: string;
  };
}

/* The data that we pass to the createConversationMutation
  as argument */
export interface CreateConversationInput {
  participantsIds: Array<string>;
}

/* Structure of the conversations that are populated with the 
  reusable prisma query (generated by prisma) named as 
  "populateParticipantsAndLatestMessage" */
export type PopulatedConversation = Prisma.ConversationGetPayload<{
  include: typeof populateParticipantsAndLatestMessage;
}>;

export interface ConversationCreationSubscriptionPayload {
  conversationCreation: PopulatedConversation;
}
